version: "3.9"
name: jija


services:
  db:
    image: postgres:latest

    environment:
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: test_base

  app:
    image: jija-dev
    build:
      dockerfile: dev/Dockerfile
      context: ..

    ports:
      - "8081:8080"

    volumes:
      - ./service:/app
      - ./entrypoint.sh:/entrypoint.sh
      - ./../jija_orm/dist:/jija_orm

    entrypoint: ["bash", "/entrypoint.sh"]
    command: "python main.py run"