version: "3.9"
name: jija


services:
  db:
    image: postgres:latest

#    ports:
#      - "5432:5432"

    environment:
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: test_base

  app:
    image: jija-dev
    build:
      dockerfile: dev/Dockerfile
      context: ..

    depends_on:
      - db

    ports:
      - "8080:8080"

    volumes:
      - ./service:/app
#      - ../tests:/tests
      - ./entrypoint.sh:/entrypoint.sh
      - ./../../jija-orm/dist:/jija_orm
      - ./../jija:/usr/local/lib/python3.10/site-packages/jija

    entrypoint: ["bash", "/entrypoint.sh"]
    command: "python main.py run"