version: "3.9"


services:
  db:
    image: postgres:latest

    environment:
      POSTGRES_PASSWORD: "0000"
      POSTGRES_DB: test_base

  app:
    build:
      dockerfile: integration_tests/Dockerfile
      context: ..

    ports:
      - "8080:8080"

    volumes:
      - ./service:/app
      - ./entrypoint.sh:/entrypoint.sh

    entrypoint: bash /entrypoint.sh